cat = {
    'linhas_apoio' : ['linhas', 'apoio'],
    'phone_model' : ['modelos', 'telemóveis','pontos'],
    'brand_phones' : ['comprar','telemóvel','preço'],
    'top_phones' : ['top','telemóveis','melhores'],
    'promo_phones' : ['promoções','telemóveis'],
    'new_phones' : ['novidades','novos','telemóveis'],
    'ofer_phones' : ['oferta','telemóveis'],
    'prest_phones' : ['prestações','prestação','telemóveis'],
    'points_phones' : ['pontos','telemóveis'],
    'phones_by_price' : ['preço','telemóveis'],
    'wtf_name' : '',
    'stores_by_zone' : ['lojas'],
    'store_address' : '',
}

categoria = {
    'bilhete' : 'cinema',
    'cinema' : 'cinema',
    'router' : 'tecnico',
    'aplicação' : 'tecnico',
    'site' : 'servicos',
    'óculos 3D': 'cinema',
    'gelado': 'cinema',
    'pipocas': 'cinema',
    'doces': 'cinema',
    'bebida': 'cinema',
    'oscares': 'cinema',
    'ator': 'cinema',
    'filme': 'cinema',
    'sessão': 'cinema',
    'ecrã': 'cinema',
    'cinema': 'cinema',
    'lugar': 'cinema',
    'audiência': 'cinema',
    'projetor': 'cinema',
    'animação': 'cinena',
    'bollywood': 'cinema',
    'CGI': 'cinema',
    'hollywood': 'cinema',
    'IMAX': 'cinema',
    'estúdio': 'cinema',
    'grande ecrã': 'cinema'
}
