cat = {
    'linhas_apoio' : ['linhas','linha','apoio','assunto','número','contacto','contactos','empresa','empresas','aderir','informações','adicionais','informação','adicional','serviços','chamada','chamadas','ligar'],
    'phone_model' : ['modelos','modelo','telemóvel','telemóveis'],
    'brand_phones' : ['marca','marcas','comprar','telemóvel','telemóveis','preço'],
    'top_phones' : ['top','telemóvel','telemóveis','melhores','link'],
    'promo_phones' : ['promoções','promoção','desconto','descontos','barato','baratos','telemóvel','telemóveis'],
    'new_phones' : ['novidades','novos','telemóvel','telemóveis','recente','recentes'],
    'ofer_phones' : ['oferta','telemóvel','telemóveis'],
    'prest_phones' : ['prestações','prestação','telemóvel','telemóveis'],
    'points_phones' : ['ponto','pontos','telemóvel','telemóveis'],
    'phones_by_price' : ['ordenar','preço','telemóvel','telemóveis'],
    'all_wtf' : ['tarifários','telemóvel','wtf']
    'wtf_name' : ['tarifário','wtf'],
    'stores_by_zone' : ['loja','lojas','zona'],
    'store_address' : ['morada','loja','lojas'],
}

categoria = {
    'bilhete' : 'cinema',
    'cinema' : 'cinema',
    'router' : 'tecnico',
    'aplicação' : 'tecnico',
    'site' : 'servicos',
    'óculos 3D': 'cinema',
    'gelado': 'cinema',
    'pipocas': 'cinema',
    'doces': 'cinema',
    'bebida': 'cinema',
    'oscares': 'cinema',
    'ator': 'cinema',
    'filme': 'cinema',
    'sessão': 'cinema',
    'ecrã': 'cinema',
    'cinema': 'cinema',
    'lugar': 'cinema',
    'audiência': 'cinema',
    'projetor': 'cinema',
    'animação': 'cinena',
    'bollywood': 'cinema',
    'CGI': 'cinema',
    'hollywood': 'cinema',
    'IMAX': 'cinema',
    'estúdio': 'cinema',
    'grande ecrã': 'cinema'
}
