categoria = {
    'bilhete' : 'cinema',
    'cinema' : 'cinema',
    'router' : 'tecnico',
    'aplicação' : 'tecnico',
    'site' : 'servicos',
    'óculos 3D': 'cinema',
    'gelado': 'cinema',
    'pipocas': 'cinema',
    'doces': 'cinema',
    'bebida': 'cinema',
    'oscares': 'cinema',
    'ator': 'cinema',
    'filme': 'cinema',
    'sessão': 'cinema',
    'ecrã': 'cinema',
    'cinema': 'cinema',
    'lugar': 'cinema',
    'audiência': 'cinema',
    'projetor': 'cinema',
    'animação': 'cinena',
    'bollywood': 'cinema',
    'CGI': 'cinema',
    'hollywood': 'cinema',
    'IMAX': 'cinema',
    'estúdio': 'cinema',
    'grande ecrã': 'cinema'
}
