# example, on some cinemas end-points 'lat' and 'lon' are required or 'search_term'
cat = [
    {
        'request': '/fs_scrapper/linhas_apoio',
        'service': 'FS_SCRAPER',
        'words': [(r'linhas?', 1.0), (r'apoio', 1.0), (r'assunto', 1.0),(r'numero', 1.0), (r'contactos?', 1.0), (r'empresas?', 1.0), (r'aderir', 1.0),
                  (r'informac(ao|oes)', 1.0), (r'servicos', 1.0), (r'chamadas?', 1.0), (r'assistente', 1.0), (r'linhas? de apoio', 2.0)],
        'paramsRequired': {},
        'paramsOptional': {'subject': 'SUBJECT'},
        'locationParam': {},
        'canRequestWithoutParams': True,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/fs_scrapper/brand_phones',
        'service': 'FS_SCRAPER',
        'words': [(r'modelos?', 1.0), (r'marcas?', 1.0), (r'telemove(l|is)', 1.0), (r'vida', 1.0), (r'telemove(l|is).+marcas?', 2.0)],
        'paramsRequired': {},
        'paramsOptional': {'0':'ORG', '0':'PRODUCT'},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': True,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/fs_scrapper/top_phones',
        'service': 'FS_SCRAPER',
        'words': [(r'top', 1.0), (r'telemove(l|is)', 1.0), (r'melhor(es)?', 1.5)],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': True,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/fs_scrapper/promo_phones',
        'service': 'FS_SCRAPER',
        'words': [(r'promo(cao|coes)?', 1.5), (r'descontos?', 1.0), (r'baratos?', 1.0), (r'telemove(l|is)', 1.0), (r'telemove(l|is).+promo(cao|coes)?', 2.0)],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': True,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/fs_scrapper/new_phones',
        'service': 'FS_SCRAPER',
        'words': [(r'novidades?', 1.0),(r'novos?', 1.0),(r'telemove(l|is)', 1.0),(r'recentes?', 1.0), (r'telemove(l|is).+novos?', 2.0), (r'telemove(l|is).+recentes?', 2.0)],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': True,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/fs_scrapper/ofer_phones',
        'service': 'FS_SCRAPER',
        'words': [(r'(com )?ofertas?', 1.0),(r'telemove(l|is)', 1.0), (r'extra', 1.0)],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': True,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/fs_scrapper/prest_phones',
        'service': 'FS_SCRAPER',
        'words': [(r'prestac(ao|oes)', 1.0),(r'telemove(l|is)', 1.0), (r'pagamentos? a prestac(ao|oes)', 2.0)],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': True,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/fs_scrapper/points_phones',
        'service': 'FS_SCRAPER',
        'words': [(r'pontos?', 1.0),(r'telemove(l|is)', 1.0)],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': True,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/fs_scrapper/phones_price',
        'service': 'FS_SCRAPER',
        'words': [(r'preco', 1.0),(r'telemove(l|is)', 1.0), (r'preco maximo', 1.0), (r'preco minimo', 1.0), (r'preco entre', 2.0)],
        'paramsRequired': {'0':'MONEY', '1':'MONEY'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, forneça um valor mínimo e um valor máximo.'
    },
    {
        'request': '/fs_scrapper/phones_brand_price',
        'service': 'FS_SCRAPER',
        'words': [(r'marcas?', 1.0),(r'preco', 1.0),(r'telemove(l|is)', 1.0)],
        'paramsRequired': {'0':'ORG', '1':'MONEY', '2':'MONEY'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, forneça uma marca e um valor mínimo e um valor máximo.'
    },
    {
        'request': '/fs_scrapper/phones_brand_promo',
        'service': 'FS_SCRAPER',
        'words': [(r'marcas?', 1.0),(r'promoc(ao|oes)', 1.0),(r'descontos?', 1.0),(r'baratos?', 1.0),(r'telemove(l|is)', 1.0)],
        'paramsRequired': {'0':'ORG'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, diga-nos a marca de telemóveis que procura.'
    },
    {
        'request': '/fs_scrapper/phones_promo_price',
        'service': 'FS_SCRAPER',
        'words': [(r'promoc(ao|oes)', 1.0),(r'descontos?', 1.0),(r'baratos?', 1.0),(r'preco', 1.0),(r'telemove(l|is)', 1.0)],
        'paramsRequired': {'0':'MONEY', '1':'MONEY'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, forneça um valor mínimo e um valor máximo.'
    },
    {
        'request': '/fs_scrapper/new_phones_brand',
        'service': 'FS_SCRAPER',
        'words': [(r'marcas?', 1.0),(r'novidades', 1.0),(r'novos?', 1.0),(r'telemove(l|is)', 1.0),(r'recentes?', 1.0)],
        'paramsRequired': {'0':'ORG'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, diga-nos a marca de telemóveis que procura.'
    },
    {
        'request': '/fs_scrapper/all_wtf',
        'service': 'FS_SCRAPER',
        'words': [(r'tarifarios', 1.0), (r'todos', 1.0), (r'telemovel', 1.0), (r'wtf', 1.0), (r'todos (os )?tarifarios', 2.0)],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': True,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''

    },
    {
        'request': '/fs_scrapper/wtf_name',
        'service': 'FS_SCRAPER',
        'words': [(r'tarifario', 1.0),(r'telemovel', 1.0),(r'wtf', 1.0)],
        'paramsRequired': {'0':'TARIFF'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, diga-nos o nome do tarifário WTF que pretende.'

    },
    {
        'request': '/fs_scrapper/stores',
        'service': 'FS_SCRAPER',
        'words': [(r'lojas?', 1.0),(r'zona', 1.0),(r'onde', 1.0),(r'est(a|ao)', 1.0)],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {'search_term':'GPE', 'lat':'', 'lon':''},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, diga-nos a zona do país que procura.'
    },
    {
        'request': '/fs_scrapper/store_address',
        'service': 'FS_SCRAPER',
        'words': [(r'morada', 1.0), (r'rua', 1.0), (r'lojas?', 1.0), (r'lojas?.+rua', 1.5), (r'lojas?.+morada', 1.5)],
        'paramsRequired': {'0':'ADDRESS'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, diga-nos a morada da loja que procura.'
    },
    {
        'request': '/fs_scrapper/specific_package',
        'service': 'FS_SCRAPER',
        'words': [(r'pacote', 1.0)],
        'paramsRequired': {'0':'PACKAGE_TYPE', '1':'PACKAGE'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, diga-nos o tipo (fibra ou satélite) e o nome do pacote que procura.'
    },
    {
        'request': '/fs_scrapper/packages',
        'service': 'FS_SCRAPER',
        'words': [(r'pacotes', 1.0)],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': True,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/fs_scrapper/fiber_packages',
        'service': 'FS_SCRAPER',
        'words': [(r'pacotes', 1.0), (r'fibra', 1.0), (r'pacotes.+fibra', 1.0)],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': True,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/fs_scrapper/satelite_packages',
        'service': 'FS_SCRAPER',
        'words': [(r'pacotes', 1.0), (r'satelite', 1.0), (r'pacotes.+satelite', 1.0)],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': True,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/fs_scrapper/packages_service',
        'service': 'FS_SCRAPER',
        'words': [(r'pacotes?', 1.0),(r'servicos?', 1.0),(r'TV', 1.0), (r'NET', 1.0), (r'TV+NET', 1.0), (r'TV+VOZ', 1.0),
                  (r'TV+NET+VOZ', 1.0)],
        'paramsRequired': {'0':'PACKAGE_SERVICE'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, diga-nos os serviços que procura (TV, NET, TV+NET, TV+VOZ, TV+NET+VOZ'
    },
    {
        'request': '/fs_scrapper/packages_price',
        'service': 'FS_SCRAPER',
        'words': [(r'ordenar', 1.0),(r'preco', 1.0),(r'pacotes?', 1.0)],
        'paramsRequired': {'0':'MONEY', '1':'MONEY'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, forneça um valor mínimo e um valor máximo.'
    },
    {
        'request': '/fs_scrapper/packages_service_price',
        'service': 'FS_SCRAPER',
        'words': [(r'pacotes?', 1.0), (r'servicos?', 1.0), (r'TV', 1.0), (r'NET', 1.0), (r'TV+NET', 1.0), (r'TV+VOZ', 1.0),
                  (r'TV+NET+VOZ', 1.0), (r'ordenar', 1.0),(r'preco', 1.0)],
        'paramsRequired': {'0':'PACKAGE_SERVICE','1':'MONEY', '2':'MONEY'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, forneça o serviço que pretende e um valor mínimo e um valor máximo.'
    },
    {
        'request': '/fs_scrapper/fiber_packages_price',
        'service': 'FS_SCRAPER',
        'words': [(r'pacotes', 1.0), (r'fibra', 1.0), (r'ordenar', 1.0),(r'preco', 1.0)],
        'paramsRequired': {'0':'MONEY', '1':'MONEY'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, forneça um valor mínimo e um valor máximo.'
    },
    {
        'request': '/fs_scrapper/satelite_packages_price',
        'service': 'FS_SCRAPER',
        'words': [(r'pacotes', 1.0), (r'satelite', 1.0), (r'ordenar', 1.0),(r'preco', 1.0)],
        'paramsRequired': {'0':'MONEY', '1':'MONEY'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, forneça um valor mínimo e um valor máximo.'
    },
    {
        'request': '/fs_scrapper/fiber_packages_service',
        'service': 'FS_SCRAPER',
        'words': [(r'pacotes', 1.0), (r'fibra', 1.0), (r'servicos?', 1.0), (r'TV', 1.0), (r'NET', 1.0), (r'TV+NET', 1.0),
                  (r'TV+VOZ', 1.0), (r'TV+NET+VOZ', 1.0)],
        'paramsRequired': {'0':'PACKAGE_SERVICE'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, diga-nos os serviços que procura (TV, NET, TV+NET, TV+VOZ, TV+NET+VOZ'
    },
    {
        'request': '/fs_scrapper/satelite_packages_service',
        'service': 'FS_SCRAPER',
        'words': [(r'pacotes', 1.0), (r'satelite', 1.0), (r'servicos?', 1.0), (r'TV', 1.0), (r'NET', 1.0), (r'TV+NET', 1.0),
                  (r'TV+VOZ', 1.0), (r'TV+NET+VOZ', 1.0)],
        'paramsRequired': {'0':'PACKAGE_SERVICE'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, diga-nos os serviços que procura (TV, NET, TV+NET, TV+VOZ, TV+NET+VOZ'
    },
    # CINEMAS
    {
        'request': '/scrapper/cinemas/search',
        'service': 'CINEMA_SCRAPER',
        'words': [(r'cinema', 1.0), (r'perto', 1.0), (r'proximos?', 1.0), (r'aqui', 1.0), (r'localidade', 1.0), (r'cidade', 1.0),
                  (r'sitio', 1.0), (r'distrito', 1.0), (r'concelho', 1.0), (r'morada', 1.0), (r'cinemas?.+perto', 2.0),
                  (r'cinemas?.+aqui', 1.0), (r'cinemas?.+proximos?', 1.0)],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {'search_term':'GPE', 'lat':'', 'lon':''},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/scrapper/movies/by_cinema',
        'service': 'CINEMA_SCRAPER',
        'words': [(r'cinemas?', 1.0), (r'perto', 1.0), (r'proximo', 1.0), (r'estou', 1.0), (r'aqui', 1.0), (r'localidade', 1.0),
                  (r'cidade', 1.0), (r'sitio', 1.0), (r'distrito', 1.0), (r'concelho', 1.0), (r'morada', 1.0), (r'filmes?', 1.0),
                  (r'cinemas?.+proximos?', 1.5), (r'filmes? nos? cinemas?', 2.0)],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {'search_term':'GPE', 'lat':'', 'lon':''},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/scrapper/movies/search',
        'service': 'CINEMA_SCRAPER',
        'words': [(r'filme', 1.0), (r'pelicula', 1.0), (r'video', 1.0), (r'procura', 1.0), (r'consulta', 1.0), (r'filmes?\.(com|de|sobre)', 2.0)],
        'paramsRequired': {},
        'paramsOptional': {'genre':'MOVIE_GENRE', 'cast':'PERSON', 'producer':'PERSON', 'synopsis':'SYNOPSIS', 'age':'CARDINAL'},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': True,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/scrapper/movies/releases',
        'service': 'CINEMA_SCRAPER',
        'words': [(r'filme', 1.0), (r'pelicula', 1.0), (r'video', 1.0), (r'estreias?', 1.0), (r'novo', 1.0), (r'estrear', 1.0),
                  (r'lancamento', 1.0), (r'filmes? a sair', 1.5), (r'filmes?.+estrear', 2.0), (r'filmes?.+estreias?', 2.0),
                  (r'filmes?.+novos?', 1.0)],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': True,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/scrapper/movies/details',
        'service': 'CINEMA_SCRAPER',
        'words': [(r'filme', 1.0), (r'pelicula', 1.0), (r'video', 1.0), (r'detalhes', 1.0), (r'informac(ao|oes)', 1.0),
                  (r'sobre', 1.0), (r'casting', 1.0), (r'ator', 1.0), (r'produtor', 1.0), (r'realizador', 1.0), (r'tipo', 1.0),
                  (r'genero', 1.0), (r'categoria', 1.0), (r'sinopse', 1.0), (r'historia', 1.0), (r'restricao', 1.0), (r'criancas', 1.0),
                  (r'adultos', 1.0), (r'sobre o filme', 1.0), (r'informac(ao|oes) do filme', 2.0)],
        'paramsRequired': {'0':'WORK OF ART'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/scrapper/sessions/by_duration',
        'service': 'CINEMA_SCRAPER',
        'words': [(r'sess(ao|oes)', 1.0), (r'sess(ao|oes)', 1.0), (r'exibic(ao|oes)', 1.0), (r'duracao', 1.0), (r'tempo', 1.0),
                  (r'tamanho', 1.0), (r'demora', 1.0), (r'extensao', 1.0), (r'minutos', 1.0), (r'horas?', 1.0), (r'sess(ao|oes) ate', 1.0),
                  (r'sess(ao|oes) com menos', 2.5)],
        'paramsRequired': {'0':'TIME'},
        'paramsOptional': {'date':'DATE', 'start_time':'TIME', 'end_time':'TIME'},
        'locationParam': {'search_term':'GPE', 'lat':'', 'lon':''},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/scrapper/sessions/next_sessions',
        'service': 'CINEMA_SCRAPER',
        'words': [(r'sess(ao|oes)', 1.0), (r'exibic(ao|oes)', 1.0), (r'proxim[oa]s', 1.0), (r'agora', 1.0), (r'seguintes?', 1.0),
                  (r'prestes', 1.0), (r'proximas? sess(ao|oes)', 2.5), (r'proximas? exibic(ao|oes)', 2.5)],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {'search_term':'GPE', 'lat':'', 'lon':''},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/scrapper/sessions/by_movie',
        'service': 'CINEMA_SCRAPER',
        'words': [(r'sess(ao|oes)', 1.0), (r'exibic(ao|oes)', 1.0), (r'filme', 1.0), (r'sess(ao|oes) dos? filmes?', 2.0)],
        'paramsRequired': {'0':'WORK OF ART'},
        'paramsOptional': {'date':'DATE', 'start_time':'TIME', 'end_time':'TIME'},
        'locationParam': {'search_term':'GPE', 'lat':'', 'lon':''},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/scrapper/sessions/by_date',
        'service': 'CINEMA_SCRAPER',
        'words': [(r'sess(ao|oes)', 1.0), (r'exibic(ao|oes)', 1.0), (r'proximas', 1.0), (r'dia', 1.0), (r'horas?', 1.0),
                  (r'inicio', 1.0), (r'fim', 1.0), (r'hoje', 1.0), (r'amanha', 1.0)],
        'paramsRequired': {},
        'paramsOptional': {'date':'DATE', 'start_time':'TIME', 'end_time':'TIME'},
        'locationParam': {'search_term':'GPE', 'lat':'', 'lon':''},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    }
]
