# example, on some cinemas end-points 'lat' and 'lon' are required or 'search_term'
cat = [
    {
        'request': '/fs_scrapper/linhas_apoio',
        'service': 'FS_SCRAPER',
        'words': [r'linhas?', r'apoio', 'assunto',r'numero', r'contactos?', r'empresas?', r'aderir', r'informac(ao|oes)', r'servicos', r'chamadas?', r'assistente', r'linhas? de apoio'],
        'paramsRequired': {},
        'paramsOptional': {'subject': 'SUBJECT'},
        'locationParam': {},
        'canRequestWithoutParams': True,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/fs_scrapper/brand_phones',
        'service': 'FS_SCRAPER',
        'words': [r'modelos?', r'marcas?', r'telemove(l|is)', r'vida', r'telemove(l|is).+marcas?'],
        'paramsRequired': {},
        'paramsOptional': {'0':'ORG', '0':'PRODUCT'},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': True,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/fs_scrapper/top_phones',
        'service': 'FS_SCRAPER',
        'words': [r'top', r'telemove(l|is)', r'melhor(es)?'],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': True,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/fs_scrapper/promo_phones',
        'service': 'FS_SCRAPER',
        'words': [r'promoc(ao|oes)', r'descontos?', r'baratos?', r'telemove(l|is)', r'telemove(l|is).+promoc(ao|oes)'],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': True,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/fs_scrapper/new_phones',
        'service': 'FS_SCRAPER',
        'words': [r'novidades?',r'novos?',r'telemove(l|is)',r'recentes?', r'telemove(l|is).+novos?', r'telemove(l|is).+recentes?'],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': True,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/fs_scrapper/ofer_phones',
        'service': 'FS_SCRAPER',
        'words': [r'(com )?ofertas?',r'telemove(l|is)', r'extra'],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': True,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/fs_scrapper/prest_phones',
        'service': 'FS_SCRAPER',
        'words': [r'prestac(ao|oes)',r'telemove(l|is)', r'pagamentos? a prestac(ao|oes)'],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': True,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/fs_scrapper/points_phones',
        'service': 'FS_SCRAPER',
        'words': [r'pontos?',r'telemove(l|is)'],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': True,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/fs_scrapper/phones_price',
        'service': 'FS_SCRAPER',
        'words': [r'preco',r'telemove(l|is)', r'preco maximo', r'preco minimo', r'preco entre'],
        'paramsRequired': {'0':'MONEY', '1':'MONEY'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, forneça um valor mínimo e um valor máximo.'
    },
    {
        'request': '/fs_scrapper/phones_brand_price',
        'service': 'FS_SCRAPER',
        'words': [r'marcas?',r'preco',r'telemove(l|is)'],
        'paramsRequired': {'0':'ORG', '1':'MONEY', '2':'MONEY'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, forneça uma marca e um valor mínimo e um valor máximo.'
    },
    {
        'request': '/fs_scrapper/phones_brand_promo',
        'service': 'FS_SCRAPER',
        'words': [r'marcas?',r'promoc(ao|oes)',r'descontos?',r'baratos?',r'telemove(l|is)'],
        'paramsRequired': {'0':'ORG'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, diga-nos a marca de telemóveis que procura.'
    },
    {
        'request': '/fs_scrapper/phones_promo_price',
        'service': 'FS_SCRAPER',
        'words': [r'promoc(ao|oes)',r'descontos?',r'baratos?',r'preco',r'telemove(l|is)'],
        'paramsRequired': {'0':'MONEY', '1':'MONEY'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, forneça um valor mínimo e um valor máximo.'
    },
    {
        'request': '/fs_scrapper/new_phones_brand',
        'service': 'FS_SCRAPER',
        'words': [r'marcas?',r'novidades',r'novos?',r'telemove(l|is)',r'recentes?'],
        'paramsRequired': {'0':'ORG'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, diga-nos a marca de telemóveis que procura.'
    },
    {
        'request': '/fs_scrapper/all_wtf',
        'service': 'FS_SCRAPER',
        'words': [r'tarifarios', r'todos', r'telemovel', r'wtf', r'todos (os )?tarifarios'],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': True,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''

    },
    {
        'request': '/fs_scrapper/wtf_name',
        'service': 'FS_SCRAPER',
        'words': [r'tarifario',r'telemovel',r'wtf'],
        'paramsRequired': {'0':'TARIFF'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, diga-nos o nome do tarifário WTF que pretende.'

    },
    {
        'request': '/fs_scrapper/stores',
        'service': 'FS_SCRAPER',
        'words': [r'lojas?',r'zona',r'onde',r'est(a|ao)'],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {'search_term':'GPE', 'lat':'', 'lon':''},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, diga-nos a zona do país que procura.'
    },
    {
        'request': '/fs_scrapper/store_address',
        'service': 'FS_SCRAPER',
        'words': [r'morada', r'rua', r'lojas?', r'lojas?.+rua', r'lojas?.+morada'],
        'paramsRequired': {'0':'ADDRESS'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, diga-nos a morada da loja que procura.'
    },
    {
        'request': '/fs_scrapper/specific_package',
        'service': 'FS_SCRAPER',
        'words': [r'pacote'],
        'paramsRequired': {'0':'PRODUCT', '1':'PACKAGE'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, diga-nos o tipo (fibra ou satélite) e o nome do pacote que procura.'
    },
    {
        'request': '/fs_scrapper/packages',
        'service': 'FS_SCRAPER',
        'words': [r'pacotes'],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': True,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/fs_scrapper/fiber_packages',
        'service': 'FS_SCRAPER',
        'words': [r'pacotes', r'fibra', r'pacotes.+fibra'],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': True,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/fs_scrapper/satelite_packages',
        'service': 'FS_SCRAPER',
        'words': [r'pacotes', r'satelite', r'pacotes.+satelite'],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': True,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/fs_scrapper/packages_service',
        'service': 'FS_SCRAPER',
        'words': [r'pacotes?',r'servicos?',r'TV', r'NET', r'TV+NET', r'TV+VOZ', r'TV+NET+VOZ'],
        'paramsRequired': {'0':'PACKAGE'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, diga-nos os serviços que procura (TV, NET, TV+NET, TV+VOZ, TV+NET+VOZ'
    },
    {
        'request': '/fs_scrapper/packages_price',
        'service': 'FS_SCRAPER',
        'words': [r'ordenar',r'preco',r'pacotes?'],
        'paramsRequired': {'0':'MONEY', '1':'MONEY'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, forneça um valor mínimo e um valor máximo.'
    },
    {
        'request': '/fs_scrapper/packages_service_price',
        'service': 'FS_SCRAPER',
        'words': [r'pacotes?', r'servicos?', r'TV', r'NET', r'TV+NET', r'TV+VOZ', r'TV+NET+VOZ', r'ordenar',r'preco'],
        'paramsRequired': {'0':'PACKAGE','1':'MONEY', '2':'MONEY'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, forneça o serviço que pretende e um valor mínimo e um valor máximo.'
    },
    {
        'request': '/fs_scrapper/fiber_packages_price',
        'service': 'FS_SCRAPER',
        'words': [r'pacotes', r'fibra', r'ordenar',r'preco'],
        'paramsRequired': {'0':'MONEY', '1':'MONEY'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, forneça um valor mínimo e um valor máximo.'
    },
    {
        'request': '/fs_scrapper/satelite_packages_price',
        'service': 'FS_SCRAPER',
        'words': [r'pacotes', r'satelite', r'ordenar',r'preco'],
        'paramsRequired': {'0':'MONEY', '1':'MONEY'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, forneça um valor mínimo e um valor máximo.'
    },
    {
        'request': '/fs_scrapper/fiber_packages_service',
        'service': 'FS_SCRAPER',
        'words': [r'pacotes', r'fibra', r'servicos?', r'TV', r'NET', r'TV+NET', r'TV+VOZ', r'TV+NET+VOZ'],
        'paramsRequired': {'0':'PACKAGE'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, diga-nos os serviços que procura (TV, NET, TV+NET, TV+VOZ, TV+NET+VOZ'
    },
    {
        'request': '/fs_scrapper/satelite_packages_service',
        'service': 'FS_SCRAPER',
        'words': [r'pacotes', r'satelite', r'servicos?', r'TV', r'NET', r'TV+NET', r'TV+VOZ', r'TV+NET+VOZ'],
        'paramsRequired': {'0':'PACKAGE'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : 'Por favor, diga-nos os serviços que procura (TV, NET, TV+NET, TV+VOZ, TV+NET+VOZ'
    },
    # CINEMAS
    {
        'request': '/scrapper/cinemas/search',
        'service': 'CINEMA_SCRAPER',
        'words': [r'cinema', r'perto', r'proximos?', r'aqui', r'localidade', r'cidade', r'sitio', r'distrito', r'concelho', r'morada', r'cinemas?.+perto', r'cinemas?.+aqui', r'cinemas?.+proximos?'],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {'search_term':'GPE', 'lat':'', 'lon':''},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/scrapper/movies/by_cinema',
        'service': 'CINEMA_SCRAPER',
        'words': [r'cinemas?', r'perto', r'proximo', r'estou', r'aqui', r'localidade', r'cidade', r'sitio', r'distrito', r'concelho', r'morada', r'filmes?', r'cinemas?.+proximos?', r'filmes? nos? cinemas?'],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {'search_term':'GPE', 'lat':'', 'lon':''},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/scrapper/movies/search',
        'service': 'CINEMA_SCRAPER',
        'words': [r'filme', r'pelicula', r'video', r'procura', r'consulta', r'filmes?\.(com|de|sobre)'],
        'paramsRequired': {},
        'paramsOptional': {'genre':'GENRE', 'cast':'PERSON', 'producer':'PERSON', 'synopsis':'SYNOPSIS', 'age':'CARDINAL'},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': True,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/scrapper/movies/releases',
        'service': 'CINEMA_SCRAPER',
        'words': ['filme', r'pelicula', r'video', r'estreias?', r'novo', r'estrear', r'lancamento', r'filmes? a sair', r'filmes?.+estrear', r'filmes?.+estreias?', r'filmes?.+novos?'],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': True,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/scrapper/movies/details',
        'service': 'CINEMA_SCRAPER',
        'words': [r'filme', r'pelicula', r'video', r'detalhes', r'informac(ao|oes)', r'sobre', r'casting', r'ator', r'produtor', r'realizador', r'tipo', r'genero', r'categoria', r'sinopse', r'historia', r'restricao', r'criancas', r'adultos',
                  r'sobre o filme', r'informac(ao|oes) do filme'],
        'paramsRequired': {'0':'WORK OF ART'},
        'paramsOptional': {},
        'locationParam': {},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/scrapper/sessions/by_duration',
        'service': 'CINEMA_SCRAPER',
        'words': [r'sess(ao|oes)', r'sess(ao|oes)', r'exibic(ao|oes)', r'duracao', r'tempo', r'tamanho', r'demora', r'extensao', r'minutos', r'horas?', r'sess(ao|oes) ate', r'sess(ao|oes) com menos'],
        'paramsRequired': {'0':'TIME'},
        'paramsOptional': {'date':'DATE', 'start_time':'TIME', 'end_time':'TIME'},
        'locationParam': {'search_term':'GPE', 'lat':'', 'lon':''},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/scrapper/sessions/next_sessions',
        'service': 'CINEMA_SCRAPER',
        'words': [r'sess(ao|oes)', r'exibic(ao|oes)', r'proxim[oa]s', r'agora', r'seguintes?', r'prestes', r'proximas? sess(ao|oes)', r'proximas? exibic(ao|oes)'],
        'paramsRequired': {},
        'paramsOptional': {},
        'locationParam': {'search_term':'GPE', 'lat':'', 'lon':''},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/scrapper/sessions/by_movie',
        'service': 'CINEMA_SCRAPER',
        'words': [r'sess(ao|oes)', r'exibic(ao|oes)', r'filme', r'sess(ao|oes) dos? filmes?'],
        'paramsRequired': {'0':'WORK OF ART'},
        'paramsOptional': {'date':'DATE', 'start_time':'TIME', 'end_time':'TIME'},
        'locationParam': {'search_term':'GPE', 'lat':'', 'lon':''},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    },
    {
        'request': '/scrapper/sessions/by_date',
        'service': 'CINEMA_SCRAPER',
        'words': [r'sess(ao|oes)', r'exibic(ao|oes)', r'proximas', r'dia', r'horas?', r'inicio', r'fim', r'hoje', r'amanha'],
        'paramsRequired': {},
        'paramsOptional': {'date':'DATE', 'start_time':'TIME', 'end_time':'TIME'},
        'locationParam': {'search_term':'GPE', 'lat':'', 'lon':''},
        'canRequestWithoutParams': False,
        'needAtLeastOneOptionalParam': False,
        'missingRequiredParamsPhrase' : ''
    }
]
